
###
 http://localhost:5000/api/client/?PageNumber=1&PageSize=2
 

###
 http://localhost:5000/api/Soft/?PageNumber=1&PageSize=2
 

###
 http://localhost:5000/api/Soft/?PageNumber=2&PageSize=2
 

###
 http://localhost:5000/api/Soft/?PageNumber=2&PageSize=2
 

###
http://localhost:5000/api/Sale
 

